set_property IOSTANDARD LVCMOS33 [get_ports a_i_0]
set_property IOSTANDARD LVCMOS33 [get_ports b_i_0]
set_property PACKAGE_PIN L15 [get_ports a_i_0]
set_property PACKAGE_PIN M15 [get_ports b_i_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_i_0]
set_property PACKAGE_PIN K13 [get_ports reset_i_0]

set_property PACKAGE_PIN M14 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN L14 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN N14 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN N13 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
