set_property PACKAGE_PIN P14 [get_ports ds_0]
set_property PACKAGE_PIN N11 [get_ports sh_cp_0]
set_property PACKAGE_PIN N12 [get_ports st_cp_0]
set_property IOSTANDARD LVCMOS33 [get_ports ds_0]
set_property IOSTANDARD LVCMOS33 [get_ports sh_cp_0]
set_property IOSTANDARD LVCMOS33 [get_ports st_cp_0]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_i[0]}]
set_property PACKAGE_PIN L15 [get_ports {gpio_rtl_tri_i[3]}]
set_property PACKAGE_PIN M15 [get_ports {gpio_rtl_tri_i[2]}]
set_property PACKAGE_PIN L14 [get_ports {gpio_rtl_tri_i[1]}]
set_property PACKAGE_PIN M14 [get_ports {gpio_rtl_tri_i[0]}]
