@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Apr 24 16:54:21 +0200 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto a4892c34d8d0451a85fc8870cd571797 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot OEF2_LED_COUNTDOWN_behav xil_defaultlib.OEF2_LED_COUNTDOWN -log elaborate.log"
call xelab  -wto a4892c34d8d0451a85fc8870cd571797 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot OEF2_LED_COUNTDOWN_behav xil_defaultlib.OEF2_LED_COUNTDOWN -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
