set_property SRC_FILE_INFO {cfile:B:/eFPGA/FinalProject/rotary_encoder/rotary_encoder.srcs/constrs_1/new/rotary_en.xdc rfile:../../../rotary_encoder.srcs/constrs_1/new/rotary_en.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports a_i_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports b_i_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports reset_i_0]
